apiVersion: v1
kind: Service
metadata:
  name: backend-despachos-service
  namespace: devops
  labels:
    app: backend-despachos
spec:
  type: LoadBalancer
  selector:
    app: backend-despachos
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
